changelog:
  categories:
    - title: 🚀 Features
      labels: [feature, enhancement]
      collapse-after: 10
    - title: 🐛 Bug Fixes
      labels: [bug, fix]
    - title: 📦 Other Changes
      labels: [chore, docs, refactor, test]
  exclude:
    labels:
      - ignore-for-release