---
name: "Gelato"
guid: "94EA4E14-8163-4989-96FE-0A2094BC2D6A"
version: "0.8.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "lstb1t"
artifacts:
  - "Gelato.dll"
  # - "Jellyfin.Api.dll"
overview: "Stream external media."
description: >
  Stream external media.
category: "General"
changelog: >
  changelog