---
name: "Gelato"
guid: "94EA4E14-8163-4989-96FE-0A2094BC2D6A"
version: "0.1.3.0"
targetAbi: "10.10.7.0"
framework: "net8.0"
owner: "lstb1t"
artifacts:
  - "Gelato.dll"
overview: "Stream external media."
description: >
  Stream external media.
category: "General"
changelog: >
  changelog